<a href="https://colab.research.google.com/github/LyaSolis/ER/blob/main/3_data_prep_for_NER.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
import csv
import glob
import os
import pandas as pd

In [3]:
nerdf = pd.read_csv('/content/drive/MyDrive/GitHub/exBERT/data/preprocessed_data/ner_data_step1.csv', encoding='utf-8')
nerdf

        article_id token_position char_position            token label
0         27711974            1-1          0-15  Next-generation     _
1         27711974            1-2         16-26       sequencing     _
2         27711974            1-3         27-28                (     _
3         27711974            1-4         28-31              NGS     _
4         27711974            1-5         31-32                )     _
...            ...            ...           ...              ...   ...
327216  PMC4342187          182-9   29514-29522         patients     _
327217  PMC4342187         182-10   29523-29525               is     _
327218  PMC4342187         182-11   29526-29531            being     _
327219  PMC4342187         182-12   29532-29543      re-assessed     _
327220  PMC4342187         182-13   29543-29544                .     _

[327221 rows x 5 columns]

In [4]:
nerdf['label'].unique()

array(['_', 'nam', 'mutation', 'PFS', 'OR', 'demography', 'comorbidity',
       'followup', 'therapy\\_group', 'CR', 'OS', 'HR', 'CI'],
      dtype=object)

In [5]:
nerdf['token'] = nerdf['token'].str.lower()

In [6]:
ther_gr = nerdf[['token',	'label']]
ther_gr = ther_gr[ther_gr['label']=='therapy\\_group']
ther_gr['token'].unique()

array(['alemtuzumab', 'and', 'rituximab', 'granulocyte', 'macrophage',
       'colony', 'stimulating', 'factor', '(', 'gm-csf', ')', 'to',
       'therapy', 'with', 'gm', '-', 'csf', ',', 'fl', 'udarabine',
       'cyclophosphamide', 'fcr', 'pentostatin', 'bendamustine',
       'vincristine', 'prednisone', 'mc038g', 'mc0785',
       'interferon-alpha', 'ifn', 'alpha', 'chemotherapy', 'ifn-treated',
       'fludarabine', 'irradiation', '2', "'", 'chlorodeoxyadenosine',
       '2cda', 'beta', '1,3', '/', '1,6', 'd-glucan', 'beta-glucans',
       'beta-glucan', 'glucans', 'pgg-glucan', 'beta-d-glucan', 'glucan',
       'bortezomib', 'radiation', 'monoclonal', 'antibody',
       'radioimmunotherapy', 'or', 'ibritumomab', 'tiuxetan',
       'immunochemotherapy', 'epoch', 'chemotherapeutics', 'chop', '.',
       'anti-cd20', 'immunotherapy', 'chemotherapeutic', 'dasatinib',
       'fludarabine-containing', 'imatinib', 'dasatinb', 'acadesine',
       'acadra', '5', 'aminoimidazole', '4', 'carboxamide', '1',
       'd-ribofuranoside', 'aica-riboside', 'its', 'metabolite', 'zmp',
       'donor', 'lymphocyte', 'infusions', 'dli', 'x', 'anti-cd3',
       'trifunctional', 'bispecific', 'trab', 'fbta05', 'in',
       'combination', 'antibodies', 'mabs', 'ertumaxomab', 'the',
       'ibrutinib', 'pci', '32765', 'forodesine', 'bcx', '1777',
       'immucillin', 'h', 'hydrochloride', 'dguo', 'idi', 'of',
       'ad-isf35', 'viral', 'particles', 'vp', 'fludarabine-based',
       'treatment', 'ofatumumab', 'group', 'oral', 'intravenous', 'low',
       'dose', 'high', 'frequency', 'monotherapy', 'lower', 'higher',
       'par', 'flavopiridol', 'lenalidomide', 'navitoclax', 'combined',
       'alone', 'arm', 'a', 'plus', 'daily', 'for', '12', 'weeks', 'b',
       'until', 'disease', 'progression', 'unacceptable', 'toxicity', 'c',
       'chlorambucil', 'obinutuzumab', '11q22.3', 'deletion', 'cyclophos',
       'phamide', 'cyclo', 'phosphamide', 'triple', 'ibrutinibâ€“rituximab',
       'chemoimmunotherapy', 'â€“', 'chemo', 'fi', 'rit', 'uximab', 'ritux',
       'imab', 'r-b', 'clb', 'r-clb', 'r', 'versusr-clb', 'chlor',
       'ambucil', 'chloram', 'bucil', 'chlo', 'rambucil', 'ibruti', 'nib',
       'pneumonia', 'neutropenia', 'inebilizumab', 'coltuximab',
       'ravtansine', 'venetoclaxâ€“rituximab', 'venetoclaxâ€“rituxi', 'mab',
       'methylprednisolone', 'methypredisolone', 'alem', 'tuzumab',
       'r-fc', 'frontline', 'pluscyclophosphamide', 'doxorubicin',
       'andprednisone', 'duvelisib', 'toobinutuzumabÃ¾chlorambucil',
       'rituximabÃ¾chlorambucil', 'orchlorambucilalone', 'obi', 'gclb',
       'obinutuzumabisthethirdcd20', 'pinatuzumab', 'vedotin', 'without',
       'rp2d', 'both', '1.8', 'mg', 'kg', '2.4', 'levels', 'inhl', 'mcl',
       'polatuzumab', 'single', 'agent', 'mgcd0103', 'mgcd103',
       'rapamycin', 'mtor', 'everolimus', 'relapsed', 'sirolimus',
       'temsirolimus', 'inno', '406', 'nilotinib', 'tkis', "','",
       'multiple', 'bcr-abl', 'bosutinib', 'second-generation', 'other',
       'flavopiridol-glucuronide', 'flavo-g', '"flavopiridols"',
       'flavopridol', 'cyclosporine', 'tacrolimus', 'methotrexate',
       'tositumomab', 'fluconazole', 'acyclovir', 'tmp', 'smx', 'g-csf',
       'alemtuzamab', 'mono-therapy', 'meg', '01', 'cell',
       'fludarabine-induced', 'cells', 'as', 'pre', 'post', '17p13.1'],
      dtype=object)

In [7]:
nerdf['token'][nerdf['token']=='obinutuzumabisthethirdcd20'] = 'obinutuzumab is the third cd20'
nerdf['token'][nerdf['token']=='"flavopiridols"'] = 'flavopiridols'
nerdf['token'][nerdf['token']=='toobinutuzumabÃ¾chlorambucil'] = 'to obinutuzumab Ã¾ chlorambucil'
nerdf['token'][nerdf['token']=='andprednisone'] = 'and prednisone'
nerdf['token'][nerdf['token']=='pluscyclophosphamide'] = 'plus cyclophosphamide'
nerdf['token'][nerdf['token']=='rituximabÃ¾chlorambucil'] = 'rituximab Ã¾ chlorambucil'
nerdf['token'][nerdf['token']=='orchlorambucilalone'] = 'or chlorambucil alone'

In [8]:
ther_gr = nerdf[['token',	'label']]
ther_gr = ther_gr[ther_gr['label']=='therapy\\_group']
ther_gr['token'].unique()

array(['alemtuzumab', 'and', 'rituximab', 'granulocyte', 'macrophage',
       'colony', 'stimulating', 'factor', '(', 'gm-csf', ')', 'to',
       'therapy', 'with', 'gm', '-', 'csf', ',', 'fl', 'udarabine',
       'cyclophosphamide', 'fcr', 'pentostatin', 'bendamustine',
       'vincristine', 'prednisone', 'mc038g', 'mc0785',
       'interferon-alpha', 'ifn', 'alpha', 'chemotherapy', 'ifn-treated',
       'fludarabine', 'irradiation', '2', "'", 'chlorodeoxyadenosine',
       '2cda', 'beta', '1,3', '/', '1,6', 'd-glucan', 'beta-glucans',
       'beta-glucan', 'glucans', 'pgg-glucan', 'beta-d-glucan', 'glucan',
       'bortezomib', 'radiation', 'monoclonal', 'antibody',
       'radioimmunotherapy', 'or', 'ibritumomab', 'tiuxetan',
       'immunochemotherapy', 'epoch', 'chemotherapeutics', 'chop', '.',
       'anti-cd20', 'immunotherapy', 'chemotherapeutic', 'dasatinib',
       'fludarabine-containing', 'imatinib', 'dasatinb', 'acadesine',
       'acadra', '5', 'aminoimidazole', '4', 'carboxamide', '1',
       'd-ribofuranoside', 'aica-riboside', 'its', 'metabolite', 'zmp',
       'donor', 'lymphocyte', 'infusions', 'dli', 'x', 'anti-cd3',
       'trifunctional', 'bispecific', 'trab', 'fbta05', 'in',
       'combination', 'antibodies', 'mabs', 'ertumaxomab', 'the',
       'ibrutinib', 'pci', '32765', 'forodesine', 'bcx', '1777',
       'immucillin', 'h', 'hydrochloride', 'dguo', 'idi', 'of',
       'ad-isf35', 'viral', 'particles', 'vp', 'fludarabine-based',
       'treatment', 'ofatumumab', 'group', 'oral', 'intravenous', 'low',
       'dose', 'high', 'frequency', 'monotherapy', 'lower', 'higher',
       'par', 'flavopiridol', 'lenalidomide', 'navitoclax', 'combined',
       'alone', 'arm', 'a', 'plus', 'daily', 'for', '12', 'weeks', 'b',
       'until', 'disease', 'progression', 'unacceptable', 'toxicity', 'c',
       'chlorambucil', 'obinutuzumab', '11q22.3', 'deletion', 'cyclophos',
       'phamide', 'cyclo', 'phosphamide', 'triple', 'ibrutinibâ€“rituximab',
       'chemoimmunotherapy', 'â€“', 'chemo', 'fi', 'rit', 'uximab', 'ritux',
       'imab', 'r-b', 'clb', 'r-clb', 'r', 'versusr-clb', 'chlor',
       'ambucil', 'chloram', 'bucil', 'chlo', 'rambucil', 'ibruti', 'nib',
       'pneumonia', 'neutropenia', 'inebilizumab', 'coltuximab',
       'ravtansine', 'venetoclaxâ€“rituximab', 'venetoclaxâ€“rituxi', 'mab',
       'methylprednisolone', 'methypredisolone', 'alem', 'tuzumab',
       'r-fc', 'frontline', 'plus cyclophosphamide', 'doxorubicin',
       'and prednisone', 'duvelisib', 'to obinutuzumab Ã¾ chlorambucil',
       'rituximab Ã¾ chlorambucil', 'or chlorambucil alone', 'obi', 'gclb',
       'obinutuzumab is the third cd20', 'pinatuzumab', 'vedotin',
       'without', 'rp2d', 'both', '1.8', 'mg', 'kg', '2.4', 'levels',
       'inhl', 'mcl', 'polatuzumab', 'single', 'agent', 'mgcd0103',
       'mgcd103', 'rapamycin', 'mtor', 'everolimus', 'relapsed',
       'sirolimus', 'temsirolimus', 'inno', '406', 'nilotinib', 'tkis',
       "','", 'multiple', 'bcr-abl', 'bosutinib', 'second-generation',
       'other', 'flavopiridol-glucuronide', 'flavo-g', 'flavopiridols',
       'flavopridol', 'cyclosporine', 'tacrolimus', 'methotrexate',
       'tositumomab', 'fluconazole', 'acyclovir', 'tmp', 'smx', 'g-csf',
       'alemtuzamab', 'mono-therapy', 'meg', '01', 'cell',
       'fludarabine-induced', 'cells', 'as', 'pre', 'post', '17p13.1'],
      dtype=object)

In [9]:
nam_gr = nerdf[['token',	'label']]
nam_gr = nam_gr[nam_gr['label']=='nam']
nam_gr['token'].unique()

array(['reduced-intensity', 'conditioning', 'hsct', 'newly', 'diagnosed',
       'patients', 'pre-treated', 'previously', 'received', 'relapsed',
       'refractory', 'relapse', 'del', '(', '11q', ')', 'with', 'disease',
       'suffering', 'from', 'rituximab', '-', 'and', '/', 'or',
       'alemtuzumab-refractory', 'high-grade', 'non-hodgkin', 'lymphoma',
       'hg-nhl', 'progressive', 'no', 'response', 'a', 'not', 'reached',
       'purine', 'analogue', 'sensitive', 'for', 'ttt',
       'fludarabine-refractory', 'cll', 'fludarabine', 'untreated',
       'treated', 'chlorambucil', ',', 'fludara', 'bine', 'plus',
       'cyclophosphamide', 'fc', 'mitoxantrone', 'n', '13', 'alone', '7',
       'combinations', '11', 'r', 'cyclo', 'phosphamide', 'doxorubicin',
       'vincristine', 'prednisone', '3', 'hdmp', 'alemtuzumab',
       'autologous', 'stem-cell', 'transplantation', '2', 'radiotherapy',
       'prior', 'bendamustine', 'bendamus', 'tine', 'without', 'to',
       'both', 'chemotherapy', 'bend', 'amustine', 'pre-treatment',
       'incurable', 'previous', 'treatments', 'responder',
       'non-responder', 'clinical', 'cr', 'non', 'responders', 'nr',
       'progression', 'nrs', 'crs', 'group', 'respond', 'treatment'],
      dtype=object)

In [10]:
pfs_gr = nerdf[['token',	'label']]
pfs_gr = pfs_gr[pfs_gr['label']=='PFS']
pfs_gr['token'].unique()

array(['3', 'Â·', '7', '\xa0', 'months', '58%', '84%', '3.9', '13.0',
       'not', 'reached', '19', '11.6', '>', '5', 'years', '10', '(',
       'range', '4', '-', '30', ',', 'and', '6', 'rituximab', 'to',
       'fludarabine', 'cyclophosphamide', '75%', '57%', '88%', '8.1',
       '26', 'month', '7.2', '34', '7.7', '8.6', '18.9', '21.6', '8.3',
       '29.9', '16.3', '11.1', '13.1', '22.4', '96%', '90%', '52%', '89%',
       '47%', '51%', '.', '15.0', '41', '55', '2', '53', '38', 'median',
       '48', '42', '33', '51', '52', '0', '35', '89.4%', '72.9%', '90.7%',
       '62.5%', '87.7%', '88.0%', '66%', '74%', '8', '32', '40', '11',
       '39.6vs', '.29.9', '39.6', '43.2', '48%', '87%', '15', 'â‰¥', '75',
       'versus34%', '94%', '97%', '86%', '20.2', '4.2', 'â€“', '34.0',
       '29.2', '15.4', '9', '11.8', '18.3', '4.7', '6.5', '18', ')', '17',
       'v', '23.5', '9.9', '9.5', '8.2', '61%', '50%', '71%', '23.0',
       '4.0', '7.6', '0.4', '9.2', '5.1', '95%', '.75', '.59', '.55',
       '0.75', '.46', '.90', '0.59', '.33', '.78', '0.55', '0.23', '80%',
       'at', 'five', 'four', 'with', 'only', '18%', '82%'], dtype=object)

In [11]:
or_gr = nerdf[['token',	'label']]
or_gr = or_gr[or_gr['label']=='OR']
or_gr['token'].unique()

array(['9.7', 'months', '90%', '94%', '95%', '42.6%', '4.1%', '>', '70%',
       '54%', '58%', '46%', '74%', '51%', '35%', '55%', '86%', '84%',
       '47.9%', '44.6%', '33.3%', '75.0%', '21.4%', 'to', '50.0%',
       '35.7%', '60.0%', '28.0%', 'and', '32.0%', '60%', '24%', '30%',
       '28%', '85%', '88%', ',', '33%', 'withanorrof47.3%', '58.1%',
       '47%', '59%', '41%', '39%', '62%', 'thrombocytopenia', '57%',
       '75.9%', '32.1%'], dtype=object)

In [12]:
demogr_gr = nerdf[['token',	'label']]
demogr_gr = demogr_gr[demogr_gr['label']=='demography']
demogr_gr['token'].unique()

array(['69.5', 'range', '62', 'â€“', '87', '38', 'and', '84', 'years', '18',
       'of', 'age', 'or', 'older', '(', ',', '36', '-', ')', '>', '60',
       'old', '59', '40', '78', 'between', '56', '79', 'both', 'genders',
       'any', 'ethnic', 'origin', 'at', 'least', 'pediatric', 'adult',
       'median', '45', '73', '70', 'more', '=', '65', '48', '26', '74',
       'younger', 'than', '75', 'â‰¤', 'female', 'male', '30', '81', 'â‰¥',
       '72', '<', '\xa0', 'men', '69.2%', 'women', '30.8%', '61.5', '34',
       'to', '82', '56%', 'patients', 'were', '65years', '68.2%',
       'themedianagewas65years', '30to90years', 'fl',
       'themedianagewas73years', 'males', '73%', '27%', 'females', '67',
       '41', '89', '33', '31', 'was', '63', '80', 'over', '53', 'young'],
      dtype=object)

In [13]:
comorbidity_gr = nerdf[['token',	'label']]
comorbidity_gr = comorbidity_gr[comorbidity_gr['label']=='comorbidity']
comorbidity_gr['token'].unique()

array(['hyperglycemia', 'hyperbilirubinemia', 'hyponatremia', 'anemia',
       'thrombocytopenia', 'neutropenia', 'cytomegalovirus',
       'pneumocystis', 'pneumonia', 'infections', 'dyspnea',
       'hypersensitivity', 'reaction', 'skin', 'reactions',
       'opportunistic', 'cmv', 'viremia', 'back', 'pain',
       'hypophosphatemia', 'diarrhea', ',', 'fatigue', 'pyrexia', 'and',
       'nausea', 'infusion-related', 'cough', 'autoimmune', 'hemolytic',
       'hemorrhage', 'aplastic', 'fever', 'myalgia', 'hypotension',
       'hyperuricemia', '84%', '59%', 'hypertension', 'hemorrhagic',
       'events', 'cardiac', 'toxic', 'effects', 'atrial', 'fibrillation',
       'leucocytopenia', 'vascular', 'disorders', 'metabolism', 'affect',
       '-', 'ing', 'blood', 'lymphatic', 'system', 'subcutaneous',
       'tissue', 'dis', 'orders', 'soc', 'â€˜', 'lym', 'phatic', 'anaemia',
       'decreased', 'white', 'cell', 'count', 'vomiting', 'grade', '3',
       '4', 'splenomegaly', 'arthralgia', 'adverse', 'event', '(', 'ae',
       '15', 'patients', ';', '31.3%', ')', '11', '22.9%', '.',
       'treatment-related', 'aes', '58.3%', '83.3%', 'irr',
       'infestations', 'thrombocyto', 'penia', 'neu', 'tropenia',
       'leukopenia', 'infusion', 'hypertriglyceridemia', 'neutrophil',
       'lymphocyte', 'infection', 'febrile', 'non-cmv', 'pneumo', 'nia',
       'septicemia', 'sinusitis', 'cystitis', 'or', 'line', 'candidiasis',
       'encephalitis', 'hepatitis', 'to', 'hematologic', 'toxicity',
       'hypokalemia', '29%', 'andcough',
       'themostcommonteaeswereneutropenia', 'flushing', 'peripheral',
       'sensory', 'neuropathy', 'constipation'], dtype=object)

In [14]:
followup_gr = nerdf[['token',	'label']]
followup_gr = followup_gr[followup_gr['label']=='followup']
followup_gr['token'].unique()

array(['290', 'days', '(', 'range', '19', 'â€“', '1142', ')', '28',
       'months', '10', '43', '25', '6', '1', 'to', '12', 'six', '4', '-',
       '30', 'up', '3', 'weeks', '18', '5', '76', ',', '9', 'and', '24',
       'after', 'start', 'of', 'treatment', 'month', 'onset', 'the',
       'study', '20.9', '0,1', '2', '7,14', '21', '60', '84', 'injection',
       'every', 'thereafter', 'for', 'a', 'total', 'year', 'median',
       'follow-up', '2.5', 'years', '9.4', '35', '27.1', '41.2', '75',
       '31', '18.4', '18.9', '37', 'Â·', '36', '0', '33.6', '23.5', '23.3',
       '14', '29', 'maximum', 'longer', 'follow', '20', '3.8', '17',
       "','", 'three-year', '7', '4.6', 'less', 'than', 'four', '15',
       '26'], dtype=object)

In [15]:
CR_gr = nerdf[['token',	'label']]
CR_gr = CR_gr[CR_gr['label']=='CR']
CR_gr['token'].unique()

array(['27%', '37%', '24%', 'one', '30%', '2', ',', '5%', '23%', '4%',
       '2%', '17.2%', '30.3%', '72%', '9%', '66%', '36%', '10', '-',
       '17%', '21%', '29%', 'four', '65%', '14%', '19.4%', '39%',
       'andthecompleteresponserateswere27.8%', 'and0.9%', '16%'],
      dtype=object)

In [16]:
OS_gr = nerdf[['token',	'label']]
OS_gr = OS_gr[OS_gr['label']=='OS']
OS_gr['token'].unique()

array(['has', 'not', 'been', 'reached', '27', 'months', '9', 'overall',
       'survival', '83%', '70%', '90%', '81%', '79%', '34.1', '16.8',
       '18.3', '98%', '85%', '97%', '98.8%', '91.5%', '43.8', '94%',
       '96%', '95%', '84%', '23.5', '38.9', '23', '16.4', 'to', 'v',
       '17.3', '28.8', '12', '15', 'years', '50%', '28.9', '71%', '68%',
       'no', 'treatment-related', 'deaths', '2', 'patients', '10.5', '(',
       'died', 'on-study', 'five', '5', '.81', '.71', '.64', '1', 'three',
       'one', 'another', '6', 'events', 'were', 'four', 'fourteen', '3',
       '0.81', '.51', '-', '.93', ')', '0.71', '.43', '.87', '0.64',
       '.30', '.85', '14', '80%', '74%'], dtype=object)

In [17]:
HR_gr = nerdf[['token',	'label']]
HR_gr = HR_gr[HR_gr['label']=='HR']
HR_gr['token'].unique()

array(['0.1491', '0.22', '0.43', '0.25', '0.39', '1', 'Â·', '643', '0.35',
       '0.17', '0.26', '0.44', '0', '56', '67', '95%', '47', '0.523',
       '0.975', '0.16', '0.12', '0.40'], dtype=object)

In [18]:
mutation_gr = nerdf[['token',	'label']]
mutation_gr = mutation_gr[mutation_gr['label']=='mutation']
mutation_gr['token'].unique()

array(['ctdna', 'detectable', 'ctdna-negative', '13q', 'deletion', '11q',
       '17p', 'unmutated', 'ighv', 'following', ':', '17p13', '-', ';',
       '11q22.3', 'deletions', '11q22', 'â€“', 'del', '(', ')', '+', '12',
       'tp53', 'p53', 'ataxia', 'telangiectasia', 'mutated', 'atm',
       'del13q14', 'del17p', 'fbta05', '17p13.1', 'btk', 'mutations',
       'immunoglobulin', 'genes', 'variable-region', 'heavy-chain',
       'gene', 'igvh', 'zap', '70', '17', 'sf3b1', 'notch1', 'function',
       'dysfunction', 'and', 'dysfunctional', 'mutation', 'del17p13',
       'del11q22', 'without', 'ighv-unmutated', 'ighv-mutated', 'fish',
       'versusmutated', '23.1%', '76.9%', 'deleted', 'defect', 'not',
       'evaluable', 'for', 'ctdna-positive', 'ctdna-nega', 'tive',
       'f317l', 'f317v', 'bcr-abl', 'e255k', 't315i', 'm351t', 'y253h',
       'g250e', 'responsive', 'microrna', 'mutant', 'meg', '01', 'cells',
       'ig', 'v', 'h', 'status', '13q14', 'germline', 'mirnas', 'mir',
       '29c', '223', '34a', 'mediated', 'induction', '106b', 'p73',
       'activation', 'fludarabine', '21', '222', '148a', 'mirna', "','",
       '15a', '/', '16', '1', 'anti-mir', 'cdkn1a', 'bbc3', 'puma',
       'pcna', 'gadd45a', 'dependent', 'linked', 'dysfunctions', '221',
       'chemotherapy', 'aberrations'], dtype=object)

In [19]:
CI_gr = nerdf[['token',	'label']]
CI_gr = CI_gr[CI_gr['label']=='CI']
CI_gr['token'].unique()

array(['0.04071', '-', '0.5464', '95%', '0.14', 'to', '0.45', '0.24',
       '0.79', '5.3,18.3', '5.7,27.0', '13.6', ',', 'not', 'reached',
       '72', '81', '27', '38', 'months', '41', '58', '58%', '86%', '4.7',
       '11.2', '4.5', '13.0', '3.0', '16.0', '0.09', '0.28', '0.04',
       '0.17', ';', 'evaluable', '1', 'Â·', '308', 'â€“', '2', '064', ')',
       '.', '34', '9', '45', '3', '33', '44', '8', '6', '52', '0', '36',
       '55', '30', '4', '5', '42', '0.22', '0.56', '0.05', '0.54', '0.50',
       '1.36', '86.0', '93.0', '65.3', '81.3', '97.6', '100', '86.2',
       '97.0', '13.4', '21.6', '23.6', '37.7', '46', '69', '48', '92',
       '57', '29', '47', '56', '39', '65', '10', '12', '24', '90',
       '0.339', '0.806', '0.505', '1.880', '0.07', '0.20', '0.21', '0.86',
       '71', '94', '84'], dtype=object)

In [20]:
nerdf['token'][nerdf['token']=='withanorrof47.3%'] = 'with an orr of 47.3%'
nerdf['token'][nerdf['token']=='versus34%'] = 'versus 34%'
nerdf['token'][nerdf['token']=='themedianagewas65years'] = 'the median age was 65 years'
nerdf['token'][nerdf['token']=='themedianagewas73years'] = 'the median age was 73 years'
nerdf['token'][nerdf['token']=='30to90years'] = '30 to 90 years'
nerdf['token'][nerdf['token']=='andcough'] = 'and cough'
nerdf['token'][nerdf['token']=='themostcommonteaeswereneutropenia'] = 'the most common teaes were neutropenia'
nerdf['token'][nerdf['token']=='andthecompleteresponserateswere27.8%'] = 'and the complete response rates were 27.8%'
nerdf['token'][nerdf['token']=='and0.9%'] = 'and 0.9%'

In [21]:
pfs_gr = nerdf[['token',	'label']]
pfs_gr = pfs_gr[pfs_gr['label']=='PFS']
PFS_TOKS = pfs_gr['token'].unique()

or_gr = nerdf[['token',	'label']]
or_gr = or_gr[or_gr['label']=='OR']
OR_TOKS = or_gr['token'].unique()

demogr_gr = nerdf[['token',	'label']]
demogr_gr = demogr_gr[demogr_gr['label']=='demography']
DEMOGRAPHY_TOKS = demogr_gr['token'].unique()

comorbidity_gr = nerdf[['token',	'label']]
comorbidity_gr = comorbidity_gr[comorbidity_gr['label']=='comorbidity']
COMORBIDITY_TOKS = comorbidity_gr['token'].unique()

CR_gr = nerdf[['token',	'label']]
CR_gr = CR_gr[CR_gr['label']=='CR']
CR_TOKS = CR_gr['token'].unique()

FOLLOWUP_TOKS = followup_gr['token'].unique()
OS_TOKS = OS_gr['token'].unique()
HR_TOKS = HR_gr['token'].unique()
CI_TOKS = CI_gr['token'].unique()
THERAPY_TOKS = ther_gr['token'].unique()
NAM_TOKS = nam_gr['token'].unique()
MUTATION_TOKS = mutation_gr['token'].unique()

array(['_', 'nam', 'mutation', 'PFS', 'OR', 'demography', 'comorbidity',
       'followup', 'therapy\\_group', 'CR', 'OS', 'HR', 'CI'],
      dtype=object)

In [22]:
set(THERAPY_TOKS) & set(NAM_TOKS)

{'(',
 ')',
 ',',
 '-',
 '/',
 '2',
 'a',
 'alemtuzumab',
 'alone',
 'and',
 'bendamustine',
 'both',
 'chemotherapy',
 'chlorambucil',
 'cyclo',
 'cyclophosphamide',
 'disease',
 'doxorubicin',
 'fludarabine',
 'for',
 'group',
 'or',
 'phosphamide',
 'plus',
 'prednisone',
 'progression',
 'r',
 'relapsed',
 'rituximab',
 'to',
 'treatment',
 'vincristine',
 'with',
 'without'}

In [23]:
set(THERAPY_TOKS) & set(MUTATION_TOKS)

{"','",
 '(',
 ')',
 '-',
 '/',
 '01',
 '1',
 '11q22.3',
 '12',
 '17p13.1',
 'and',
 'bcr-abl',
 'cells',
 'chemotherapy',
 'deletion',
 'fbta05',
 'fludarabine',
 'for',
 'h',
 'meg',
 'without',
 'â€“'}

In [24]:
set(THERAPY_TOKS) & set(PFS_TOKS)

{'(',
 ')',
 ',',
 '-',
 '.',
 '2',
 '4',
 '5',
 'and',
 'cyclophosphamide',
 'fludarabine',
 'rituximab',
 'to',
 'with',
 'â€“'}

In [25]:
set(THERAPY_TOKS) & set(COMORBIDITY_TOKS)

{'(',
 ')',
 ',',
 '-',
 '.',
 '4',
 'and',
 'cell',
 'lymphocyte',
 'neutropenia',
 'or',
 'pneumonia',
 'to',
 'toxicity'}

In [26]:
set(THERAPY_TOKS) & set(CI_TOKS)

{')', ',', '-', '.', '1', '12', '2', '4', '5', 'to', 'â€“'}

In [27]:
set(THERAPY_TOKS) & set(HR_TOKS)

{'1'}

In [28]:
set(THERAPY_TOKS) & set(OS_TOKS)

{'(', ')', '-', '1', '12', '2', '5', 'to'}

In [29]:
set(THERAPY_TOKS) & set(CR_TOKS)

{',', '-', '2'}

In [30]:
set(THERAPY_TOKS) & set(DEMOGRAPHY_TOKS)

{'(', ')', ',', '-', 'and', 'both', 'fl', 'of', 'or', 'to', 'â€“'}

In [31]:
set(THERAPY_TOKS) & set(OR_TOKS)

{',', 'and', 'to'}

In [ ]:
NAM_TOKS
MUTATION_TOKS
PFS_TOKS
OR_TOKS
DEMOGRAPHY_TOKS
COMORBIDITY_TOKS
FOLLOWUP_TOKS
THERAPY_TOKS
CR_TOKS
OS_TOKS
HR_TOKS
CI_TOKS

In [32]:
THERAPY_TOKS

array(['alemtuzumab', 'and', 'rituximab', 'granulocyte', 'macrophage',
       'colony', 'stimulating', 'factor', '(', 'gm-csf', ')', 'to',
       'therapy', 'with', 'gm', '-', 'csf', ',', 'fl', 'udarabine',
       'cyclophosphamide', 'fcr', 'pentostatin', 'bendamustine',
       'vincristine', 'prednisone', 'mc038g', 'mc0785',
       'interferon-alpha', 'ifn', 'alpha', 'chemotherapy', 'ifn-treated',
       'fludarabine', 'irradiation', '2', "'", 'chlorodeoxyadenosine',
       '2cda', 'beta', '1,3', '/', '1,6', 'd-glucan', 'beta-glucans',
       'beta-glucan', 'glucans', 'pgg-glucan', 'beta-d-glucan', 'glucan',
       'bortezomib', 'radiation', 'monoclonal', 'antibody',
       'radioimmunotherapy', 'or', 'ibritumomab', 'tiuxetan',
       'immunochemotherapy', 'epoch', 'chemotherapeutics', 'chop', '.',
       'anti-cd20', 'immunotherapy', 'chemotherapeutic', 'dasatinib',
       'fludarabine-containing', 'imatinib', 'dasatinb', 'acadesine',
       'acadra', '5', 'aminoimidazole', '4', 'carboxamide', '1',
       'd-ribofuranoside', 'aica-riboside', 'its', 'metabolite', 'zmp',
       'donor', 'lymphocyte', 'infusions', 'dli', 'x', 'anti-cd3',
       'trifunctional', 'bispecific', 'trab', 'fbta05', 'in',
       'combination', 'antibodies', 'mabs', 'ertumaxomab', 'the',
       'ibrutinib', 'pci', '32765', 'forodesine', 'bcx', '1777',
       'immucillin', 'h', 'hydrochloride', 'dguo', 'idi', 'of',
       'ad-isf35', 'viral', 'particles', 'vp', 'fludarabine-based',
       'treatment', 'ofatumumab', 'group', 'oral', 'intravenous', 'low',
       'dose', 'high', 'frequency', 'monotherapy', 'lower', 'higher',
       'par', 'flavopiridol', 'lenalidomide', 'navitoclax', 'combined',
       'alone', 'arm', 'a', 'plus', 'daily', 'for', '12', 'weeks', 'b',
       'until', 'disease', 'progression', 'unacceptable', 'toxicity', 'c',
       'chlorambucil', 'obinutuzumab', '11q22.3', 'deletion', 'cyclophos',
       'phamide', 'cyclo', 'phosphamide', 'triple', 'ibrutinibâ€“rituximab',
       'chemoimmunotherapy', 'â€“', 'chemo', 'fi', 'rit', 'uximab', 'ritux',
       'imab', 'r-b', 'clb', 'r-clb', 'r', 'versusr-clb', 'chlor',
       'ambucil', 'chloram', 'bucil', 'chlo', 'rambucil', 'ibruti', 'nib',
       'pneumonia', 'neutropenia', 'inebilizumab', 'coltuximab',
       'ravtansine', 'venetoclaxâ€“rituximab', 'venetoclaxâ€“rituxi', 'mab',
       'methylprednisolone', 'methypredisolone', 'alem', 'tuzumab',
       'r-fc', 'frontline', 'plus cyclophosphamide', 'doxorubicin',
       'and prednisone', 'duvelisib', 'to obinutuzumab Ã¾ chlorambucil',
       'rituximab Ã¾ chlorambucil', 'or chlorambucil alone', 'obi', 'gclb',
       'obinutuzumab is the third cd20', 'pinatuzumab', 'vedotin',
       'without', 'rp2d', 'both', '1.8', 'mg', 'kg', '2.4', 'levels',
       'inhl', 'mcl', 'polatuzumab', 'single', 'agent', 'mgcd0103',
       'mgcd103', 'rapamycin', 'mtor', 'everolimus', 'relapsed',
       'sirolimus', 'temsirolimus', 'inno', '406', 'nilotinib', 'tkis',
       "','", 'multiple', 'bcr-abl', 'bosutinib', 'second-generation',
       'other', 'flavopiridol-glucuronide', 'flavo-g', 'flavopiridols',
       'flavopridol', 'cyclosporine', 'tacrolimus', 'methotrexate',
       'tositumomab', 'fluconazole', 'acyclovir', 'tmp', 'smx', 'g-csf',
       'alemtuzamab', 'mono-therapy', 'meg', '01', 'cell',
       'fludarabine-induced', 'cells', 'as', 'pre', 'post', '17p13.1'],
      dtype=object)

In [33]:
# let's see if all tokens are labelled
nerdf['label'][nerdf['token']=='chemotherapy'] = 'therapy\_group'

In [34]:
nerdf[nerdf['token']=='chemotherapy']

        article_id token_position char_position         token           label
9887      10428194         364-26   49220-49232  chemotherapy  therapy\_group
11612     10428194          52-35     6649-6661  chemotherapy  therapy\_group
18769      1503098           1-29       190-202  chemotherapy  therapy\_group
18791      1503098           2-18       333-345  chemotherapy  therapy\_group
18848      1503098           5-11       658-670  chemotherapy  therapy\_group
...            ...            ...           ...           ...             ...
313232  PMC3134602          35-21     6844-6856  chemotherapy  therapy\_group
317211  PMC2892453          18-36     2971-2983  chemotherapy  therapy\_group
320211  PMC2892453         110-20   19488-19500  chemotherapy  therapy\_group
322475  PMC4342187          17-21     3173-3185  chemotherapy  therapy\_group
322899  PMC4342187          34-35     5867-5879  chemotherapy  therapy\_group

[181 rows x 5 columns]

In [35]:
nerdf[nerdf['token']=='immunotherapy']

,article_id,token_position,char_position,token,label
15306,10428194,154-18,25304-25317,immunotherapy,_
23771,PMC2827854,133-16,17463-17476,immunotherapy,therapy\_group
34145,PMC3702397,1-20,120-133,immunotherapy,therapy\_group
34170,PMC3702397,2-17,273-286,immunotherapy,_
38601,PMC3702397,155-9,24530-24543,immunotherapy,_
52708,PMC4114227,156-7,21799-21812,immunotherapy,_
54422,PMC4114227,225-13,31976-31989,immunotherapy,_
96939,eichhorst2016,18-43,5635-5648,immunotherapy,_
98347,eichhorst2016,47-20,13972-13985,immunotherapy,_
109442,eichhorst2016,226-25,61877-61890,immunotherapy,_
110514,eichhorst2016,254-59,68534-68547,immunotherapy,_
110724,eichhorst2016,256-113,69823-69836,immunotherapy,_
137921,hallek2010-3,77-17,20187-20200,immunotherapy,therapy\_group
139941,hallek2010-3,113-151,27982-27995,immunotherapy,_
140486,hallek2010-3,128-15,30585-30598,immunotherapy,therapy\_group
140556,hallek2010-3,130-3,30777-30790,immunotherapy,_
141555,hallek2010-3,153-24,34847-34860,immunotherapy,_
141623,hallek2010-3,155-16,35159-35172,immunotherapy,_
143424,hallek2010-3,192-33,43154-43167,immunotherapy,_
173891,nejmoa1509388,60-406,6149-6162,immunotherapy,_
202714,s12185-019-02635-9,29-21,6751-6764,immunotherapy,_
207750,s12185-019-02635-9,166-12,30660-30673,immunotherapy,_
241229,JCO,9-37,1594-1607,immunotherapy,_
272698,j,131-19,21033-21046,immunotherapy,_

In [36]:
nerdf['label'][nerdf['token']=='immunotherapy'] = 'therapy\_group'

In [37]:
nerdf['label'][nerdf['token']=='ibrutinib'] = 'therapy\_group'
nerdf[nerdf['token']=='ibrutinib']

        article_id token_position char_position      token           label
39709   PMC3772525           3-22       416-425  ibrutinib  therapy\_group
39761   PMC3772525           4-19       702-711  ibrutinib  therapy\_group
39904   PMC3772525            9-1     1510-1519  ibrutinib  therapy\_group
40255   PMC3772525           23-1     3725-3734  ibrutinib  therapy\_group
40294   PMC3772525           24-6     3942-3951  ibrutinib  therapy\_group
...            ...            ...           ...        ...             ...
327078  PMC4342187          177-6   28659-28668  ibrutinib  therapy\_group
327097  PMC4342187          178-1   28789-28798  ibrutinib  therapy\_group
327149  PMC4342187         179-17   29070-29079  ibrutinib  therapy\_group
327173  PMC4342187         180-20   29225-29234  ibrutinib  therapy\_group
327194  PMC4342187         181-10   29364-29373  ibrutinib  therapy\_group

[621 rows x 5 columns]

In [38]:
nerdf['label'][nerdf['token']=='radioimmunotherapy'] = 'therapy\_group'

In [39]:
nerdf['label'][nerdf['token']=='imatinib'] = 'therapy\_group'

In [40]:
nerdf[nerdf['token']=='immunochemotherapy']

,article_id,token_position,char_position,token,label
23015,PMC2827854,104-5,12881-12899,immunochemotherapy,therapy\_group
145315,hallek2010-3,258-1,51128-51146,immunochemotherapy,_
145597,hallek2010-3,272-7,52453-52471,immunochemotherapy,_
151723,1030698,132-38,25987-26005,immunochemotherapy,_
152702,1030698,156-49,30505-30523,immunochemotherapy,_
262001,bjh,287-114,51289-51307,immunochemotherapy,_
289872,1078-0432,251-33,36909-36927,immunochemotherapy,_

In [41]:
nerdf['label'][nerdf['token']=='immunochemotherapy'] = 'therapy\_group'

In [42]:
nerdf[nerdf['token']=='ibrutinibâ€“rituximab']

,article_id,token_position,char_position,token,label
112662,nihms-1536858,1-1,0-19,ibrutinibâ€“rituximab,_
113062,nihms-1536858,19-9,1601-1620,ibrutinibâ€“rituximab,therapy\_group
113457,nihms-1536858,31-76,3555-3574,ibrutinibâ€“rituximab,therapy\_group
113517,nihms-1536858,32-11,3878-3897,ibrutinibâ€“rituximab,therapy\_group
113564,nihms-1536858,33-17,4125-4144,ibrutinibâ€“rituximab,therapy\_group
113613,nihms-1536858,34-16,4402-4421,ibrutinibâ€“rituximab,therapy\_group
113671,nihms-1536858,35-33,4698-4717,ibrutinibâ€“rituximab,_
113697,nihms-1536858,35-59,4856-4875,ibrutinibâ€“rituximab,_
113721,nihms-1536858,36-2,4972-4991,ibrutinibâ€“rituximab,_
114795,nihms-1536858,57-14,11128-11147,ibrutinibâ€“rituximab,_
114810,nihms-1536858,58-8,11259-11278,ibrutinibâ€“rituximab,_
115046,nihms-1536858,63-4,12498-12517,ibrutinibâ€“rituximab,_
115525,nihms-1536858,76-20,15102-15121,ibrutinibâ€“rituximab,_
115888,nihms-1536858,91-10,17297-17316,ibrutinibâ€“rituximab,_
116023,nihms-1536858,96-88,17786-17805,ibrutinibâ€“rituximab,_
116208,nihms-1536858,102-28,18834-18853,ibrutinibâ€“rituximab,therapy\_group
116265,nihms-1536858,104-7,19134-19153,ibrutinibâ€“rituximab,therapy\_group
116309,nihms-1536858,105-18,19329-19348,ibrutinibâ€“rituximab,therapy\_group
116359,nihms-1536858,107-9,19667-19686,ibrutinibâ€“rituximab,_
116394,nihms-1536858,108-1,19879-19898,ibrutinibâ€“rituximab,therapy\_group
116517,nihms-1536858,111-18,20549-20568,ibrutinibâ€“rituximab,_
116577,nihms-1536858,112-33,20856-20875,ibrutinibâ€“rituximab,therapy\_group
116716,nihms-1536858,116-91,21342-21361,ibrutinibâ€“rituximab,_
116743,nihms-1536858,117-10,21529-21548,ibrutinibâ€“rituximab,_
116842,nihms-1536858,120-33,22011-22030,ibrutinibâ€“rituximab,_
116949,nihms-1536858,122-14,22535-22554,ibrutinibâ€“rituximab,therapy\_group
116990,nihms-1536858,123-17,22725-22744,ibrutinibâ€“rituximab,therapy\_group
117029,nihms-1536858,124-18,22924-22943,ibrutinibâ€“rituximab,therapy\_group
117142,nihms-1536858,126-14,23590-23609,ibrutinibâ€“rituximab,therapy\_group
117190,nihms-1536858,127-38,23871-23890,ibrutinibâ€“rituximab,_
117305,nihms-1536858,131-7,24479-24498,ibrutinibâ€“rituximab,_
117467,nihms-1536858,135-93,25132-25151,ibrutinibâ€“rituximab,_
117586,nihms-1536858,139-32,25955-25974,ibrutinibâ€“rituximab,_
117635,nihms-1536858,139-81,26264-26283,ibrutinibâ€“rituximab,_
117758,nihms-1536858,140-1,27059-27078,ibrutinibâ€“rituximab,_
117843,nihms-1536858,142-5,27650-27669,ibrutinibâ€“rituximab,_
117875,nihms-1536858,142-37,27845-27864,ibrutinibâ€“rituximab,_
117888,nihms-1536858,143-11,27942-27961,ibrutinibâ€“rituximab,_
118149,nihms-1536858,146-154,29131-29150,ibrutinibâ€“rituximab,_
118193,nihms-1536858,146-198,29364-29383,ibrutinibâ€“rituximab,_
118374,nihms-1536858,152-19,30480-30499,ibrutinibâ€“rituximab,_
118531,nihms-1536858,154-23,31427-31446,ibrutinibâ€“rituximab,_
121533,nihms-1536858,318-4,46010-46029,ibrutinibâ€“rituximab,_

In [43]:
nerdf['label'][nerdf['token']=='ibrutinibâ€“rituximab'] = 'therapy\_group'

In [48]:
nerdf[(nerdf['token']=='rituximab') & (nerdf['label']=='PFS')]

       article_id token_position char_position      token label
29765  PMC3579463          15-28     2365-2374  rituximab   PFS

In [49]:
nerdf[(nerdf['token']=='rituximab') & (nerdf['label']=='nam')]

        article_id token_position char_position      token label
34321   PMC3702397           7-54     1245-1254  rituximab   nam
243297         JCO           61-5   13913-13922  rituximab   nam
243318         JCO          61-26   13988-13997  rituximab   nam
247268         JCO         140-75   33352-33361  rituximab   nam
269706           j           37-5     6333-6342  rituximab   nam

In [47]:
nerdf[nerdf['token']=='rituximab']

        article_id token_position char_position      token           label
8322      10428194          290-1   40787-40796  rituximab               _
8438      10428194         296-12   41454-41463  rituximab               _
8977      10428194         328-34   44332-44341  rituximab               _
8981      10428194         328-38   44360-44369  rituximab               _
8990      10428194         328-47   44412-44421  rituximab               _
...            ...            ...           ...        ...             ...
315484  PMC3134602         115-11   18440-18449  rituximab  therapy\_group
326103  PMC4342187         140-27   22697-22706  rituximab               _
326148  PMC4342187         141-38   22998-23007  rituximab               _
326590  PMC4342187         157-31   25631-25640  rituximab               _
326885  PMC4342187          171-9   27536-27545  rituximab               _

[847 rows x 5 columns]

In [51]:
nerdf[(nerdf['token']=='fludarabine') & (nerdf['label']!='therapy\_group')& (nerdf['label']!='_')]

        article_id token_position char_position        token     label
29767   PMC3579463          15-30     2378-2389  fludarabine       PFS
84103   PMC4552311          98-30   17216-17227  fludarabine       nam
231955         jco          31-56     5803-5814  fludarabine       nam
234163         jco          88-36   17599-17610  fludarabine       nam
234170         jco          88-43   17626-17637  fludarabine       nam
317769  PMC2892453          34-11     6128-6139  fludarabine  mutation
320210  PMC2892453         110-19   19476-19487  fludarabine  mutation

In [52]:
nerdf[nerdf['token']=='fludarabine']

        article_id token_position char_position        token           label
18932     16611308           1-45       270-281  fludarabine  therapy\_group
19017     16611308            6-8       747-758  fludarabine  therapy\_group
20801   PMC2827854            1-9         55-66  fludarabine  therapy\_group
20869   PMC2827854            4-1       488-499  fludarabine  therapy\_group
20889   PMC2827854           5-10       609-620  fludarabine  therapy\_group
...            ...            ...           ...          ...             ...
321670  PMC2892453         167-11   27531-27542  fludarabine               _
326098  PMC4342187         140-22   22662-22673  fludarabine               _
326143  PMC4342187         141-33   22963-22974  fludarabine               _
326585  PMC4342187         157-26   25596-25607  fludarabine               _
326880  PMC4342187          171-4   27501-27512  fludarabine               _

[225 rows x 5 columns]

In [53]:
nerdf[nerdf['token']=='bendamustine']

        article_id token_position char_position         token           label
7474      10428194         258-31   36368-36380  bendamustine               _
8979      10428194         328-36   44343-44355  bendamustine               _
14655     10428194         136-28   21974-21986  bendamustine  therapy\_group
23802   PMC2827854         135-15   17681-17693  bendamustine               _
55107   PMC4134521          17-12     2506-2518  bendamustine               _
...            ...            ...           ...           ...             ...
272895           j         135-19   21895-21907  bendamustine               _
273705           j          173-1   25895-25907  bendamustine               _
279855         bjh         217-23   30798-30810  bendamustine               _
291314   1078-0432          329-6   43700-43712  bendamustine               _
320543  PMC2892453         122-43   21356-21368  bendamustine               _

[195 rows x 5 columns]

In [54]:
nerdf[(nerdf['token']=='bendamustine') & (nerdf['label']!='therapy\_group')& (nerdf['label']!='_')]

       article_id token_position char_position         token label
243284        JCO           60-8   13852-13864  bendamustine   nam
243752        JCO           77-8   16390-16402  bendamustine   nam
243767        JCO          77-23   16463-16475  bendamustine   nam

In [55]:
nerdf[nerdf['token']=='alemtuzumab']

        article_id token_position char_position        token           label
8372      10428194          293-2   41095-41106  alemtuzumab               _
10420     10428194           1-93       539-550  alemtuzumab               _
10590     10428194          18-25     1305-1316  alemtuzumab               _
10982     10428194          30-44     3335-3346  alemtuzumab               _
11149     10428194         38-116     4249-4260  alemtuzumab  therapy\_group
...            ...            ...           ...          ...             ...
301426  PMC2861142          106-8   17516-17527  alemtuzumab  therapy\_group
322607  PMC4342187           25-4     4065-4076  alemtuzumab               _
326168  PMC4342187         142-12   23126-23137  alemtuzumab               _
326962  PMC4342187         172-51   27944-27955  alemtuzumab               _
326977  PMC4342187          173-4   28009-28020  alemtuzumab               _

[236 rows x 5 columns]

In [56]:
nerdf[(nerdf['token']=='alemtuzumab') & (nerdf['label']!='therapy\_group')& (nerdf['label']!='_')]

       article_id token_position char_position        token label
234200        jco          88-73   17752-17763  alemtuzumab   nam

In [57]:
nerdf[(nerdf['token']=='alemtuzumab') & (nerdf['label']=='therapy\_group')]

        article_id token_position char_position        token           label
11149     10428194         38-116     4249-4260  alemtuzumab  therapy\_group
11386     10428194           46-7     5459-5470  alemtuzumab  therapy\_group
11758     10428194          56-14     7478-7489  alemtuzumab  therapy\_group
11781     10428194           57-7     7599-7610  alemtuzumab  therapy\_group
11803     10428194          57-29     7727-7738  alemtuzumab  therapy\_group
12013     10428194          61-36     8727-8738  alemtuzumab  therapy\_group
12683     10428194           80-4   12491-12502  alemtuzumab  therapy\_group
12738     10428194           81-9   12718-12729  alemtuzumab  therapy\_group
12783     10428194           83-7   12920-12931  alemtuzumab  therapy\_group
14411     10428194         126-16   20642-20653  alemtuzumab  therapy\_group
14420     10428194         126-25   20690-20701  alemtuzumab  therapy\_group
14583     10428194         133-39   21592-21603  alemtuzumab  therapy\_group
15845     10428194          173-6   27775-27786  alemtuzumab  therapy\_group
15852     10428194         173-13   27814-27825  alemtuzumab  therapy\_group
64623   PMC4280857           3-20       412-423  alemtuzumab  therapy\_group
64898   PMC4280857           13-2     1999-2010  alemtuzumab  therapy\_group
65072   PMC4280857          19-17     3125-3136  alemtuzumab  therapy\_group
71914   PMC4476391           1-16        94-105  alemtuzumab  therapy\_group
76800   PMC4535917           3-11       338-349  alemtuzumab  therapy\_group
76844   PMC4535917           4-39       563-574  alemtuzumab  therapy\_group
76996   PMC4535917           9-12     1376-1387  alemtuzumab  therapy\_group
77224   PMC4535917          15-19     2833-2844  alemtuzumab  therapy\_group
77227   PMC4535917           16-2     2859-2870  alemtuzumab  therapy\_group
77315   PMC4535917           19-9     3400-3411  alemtuzumab  therapy\_group
78134   PMC4535917           47-8     8046-8057  alemtuzumab  therapy\_group
78416   PMC4535917           57-9     9657-9668  alemtuzumab  therapy\_group
78693   PMC4535917           69-6   11188-11199  alemtuzumab  therapy\_group
78892   PMC4535917           76-1   12291-12302  alemtuzumab  therapy\_group
78926   PMC4535917           77-4   12503-12514  alemtuzumab  therapy\_group
79035   PMC4535917           81-3   13048-13059  alemtuzumab  therapy\_group
79217   PMC4535917           87-6   14036-14047  alemtuzumab  therapy\_group
79615   PMC4535917         103-17   16400-16411  alemtuzumab  therapy\_group
79629   PMC4535917         103-31   16494-16505  alemtuzumab  therapy\_group
80035   PMC4535917         116-14   18794-18805  alemtuzumab  therapy\_group
80059   PMC4535917         117-13   18917-18928  alemtuzumab  therapy\_group
231382         jco          19-23     2622-2633  alemtuzumab  therapy\_group
231414         jco          20-27     2820-2831  alemtuzumab  therapy\_group
231597         jco           28-2     3826-3837  alemtuzumab  therapy\_group
232124         jco         32-128     6772-6783  alemtuzumab  therapy\_group
236329         jco          142-4   28357-28368  alemtuzumab  therapy\_group
236482         jco         145-57   29203-29214  alemtuzumab  therapy\_group
301347  PMC2861142          104-9   16991-17002  alemtuzumab  therapy\_group
301398  PMC2861142         105-30   17327-17338  alemtuzumab  therapy\_group
301426  PMC2861142          106-8   17516-17527  alemtuzumab  therapy\_group

In [58]:
nerdf['label'][nerdf['token']=='alemtuzumab'] = 'therapy\_group'

In [59]:
nerdf[nerdf['token']=='chlorambucil']

        article_id token_position char_position         token           label
18278     10428194          282-1   39199-39211  chlorambucil               _
28707   PMC3108904         181-20   25646-25658  chlorambucil               _
39972   PMC3772525          12-13     1952-1964  chlorambucil               _
43569   PMC3772525         142-53   22568-22580  chlorambucil               _
91109   PMC4722809           2-20       285-297  chlorambucil  therapy\_group
...            ...            ...           ...           ...             ...
270662           j           67-8   11336-11348  chlorambucil               _
272897           j         135-21   21912-21924  chlorambucil               _
273763           j          175-3   26181-26193  chlorambucil               _
317519  PMC2892453          27-10     4698-4710  chlorambucil               _
320632  PMC2892453         125-20   21855-21867  chlorambucil  therapy\_group

[256 rows x 5 columns]

In [60]:
nerdf[(nerdf['token']=='chlorambucil') & (nerdf['label']!='therapy\_group')& (nerdf['label']!='_')]

       article_id token_position char_position         token label
231949        jco          31-50     5774-5786  chlorambucil   nam
234157        jco          88-30   17576-17588  chlorambucil   nam

In [61]:
nerdf[nerdf['token']=='phosphamide']

,article_id,token_position,char_position,token,label
98353,eichhorst2016,47-26,14014-14025,phosphamide,_
101588,eichhorst2016,125-81,30842-30853,phosphamide,_
102201,eichhorst2016,135-37,33534-33545,phosphamide,_
102373,eichhorst2016,139-37,34359-34370,phosphamide,_
102890,eichhorst2016,149-26,36608-36619,phosphamide,therapy\_group
104855,eichhorst2016,170-47,43687-43698,phosphamide,_
105001,eichhorst2016,173-29,44471-44482,phosphamide,_
105221,eichhorst2016,177-27,45501-45512,phosphamide,_
105351,eichhorst2016,179-14,46070-46081,phosphamide,_
105717,eichhorst2016,188-20,47777-47788,phosphamide,_
110235,eichhorst2016,247-46,66678-66689,phosphamide,_
110345,eichhorst2016,251-32,67384-67395,phosphamide,_
135638,hallek2010-3,19-39,8079-8090,phosphamide,_
173822,nejmoa1509388,60-337,5759-5770,phosphamide,_
182712,nejmoa1509388,307-7,49696-49707,phosphamide,_
183103,nejmoa1509388,329-9,51464-51475,phosphamide,_
234181,jco,88-54,17675-17686,phosphamide,nam

In [62]:
nerdf[nerdf['token']=='17p13.1']

        article_id token_position char_position    token     label
39881   PMC3772525           7-27     1383-1390  17p13.1         _
40035   PMC3772525          14-10     2353-2360  17p13.1  mutation
41613   PMC3772525          76-14   11738-11745  17p13.1  mutation
42548   PMC3772525          108-9   16593-16600  17p13.1  mutation
42929   PMC3772525         120-15   18677-18684  17p13.1  mutation
...            ...            ...           ...      ...       ...
326572  PMC4342187         157-13   25523-25530  17p13.1         _
326766  PMC4342187          166-4   26785-26792  17p13.1         _
326940  PMC4342187         172-29   27855-27862  17p13.1         _
327043  PMC4342187         175-27   28432-28439  17p13.1         _
327120  PMC4342187         178-24   28925-28932  17p13.1         _

[67 rows x 5 columns]

In [63]:
nerdf[(nerdf['token']=='17p13.1') & (nerdf['label']!='mutation')& (nerdf['label']!='_')]

        article_id token_position char_position    token           label
322825  PMC4342187          33-15     5446-5453  17p13.1  therapy\_group

In [64]:
nerdf['label'][nerdf['token']=='17p13.1'] = 'mutation'

In [65]:
nerdf[(nerdf['token']=='11q22.3') & (nerdf['label']!='mutation')& (nerdf['label']!='_')]

       article_id token_position char_position    token           label
93324  PMC4722809          71-43   13245-13252  11q22.3  therapy\_group

In [66]:
nerdf[nerdf['token']=='11q22.3']

           article_id token_position char_position    token           label
11195        10428194          40-17     4518-4525  11q22.3        mutation
11472        10428194          48-25     5904-5911  11q22.3        mutation
41619      PMC3772525          76-20   11769-11776  11q22.3        mutation
42932      PMC3772525         120-18   18690-18697  11q22.3        mutation
43632      PMC3772525         144-20   22987-22994  11q22.3               _
56689      PMC4134521          66-20   11802-11809  11q22.3               _
82008      PMC4552311          29-44     5750-5757  11q22.3               _
82133      PMC4552311          33-33     6392-6399  11q22.3        mutation
84091      PMC4552311          98-18   17157-17164  11q22.3        mutation
84544      PMC4552311         112-26   19293-19300  11q22.3        mutation
85656      PMC4552311         143-37   25092-25099  11q22.3               _
91833      PMC4722809          25-30     4669-4676  11q22.3        mutation
93324      PMC4722809          71-43   13245-13252  11q22.3  therapy\_group
93516      PMC4722809          76-34   14285-14292  11q22.3               _
95013      PMC4722809         120-45   22711-22718  11q22.3               _
114773  nihms-1536858          56-17   10996-11003  11q22.3               _
116386  nihms-1536858         107-36   19850-19857  11q22.3               _
117779  nihms-1536858         140-22   27215-27222  11q22.3               _
173928  nejmoa1509388         60-443     6390-6397  11q22.3               _
175636  nejmoa1509388         106-45   15962-15969  11q22.3               _
175843  nejmoa1509388         111-36   17063-17070  11q22.3               _
176419  nejmoa1509388        126-188   19690-19697  11q22.3               _
177112  nejmoa1509388        133-312   22420-22427  11q22.3               _
179125  nejmoa1509388        186-302   32671-32678  11q22.3               _
294166     PMC2779118           6-18       741-748  11q22.3               _
296500     PMC2779118          86-19   13636-13643  11q22.3        mutation
317188     PMC2892453          18-13     2844-2851  11q22.3        mutation
326298     PMC4342187         146-42   23897-23904  11q22.3               _

In [67]:
nerdf['label'][nerdf['token']=='11q22.3'] = 'mutation'

In [68]:
nerdf[nerdf['token']=='pneumonia']

,article_id,token_position,char_position,token,label
12821,10428194,85-7,13143-13152,pneumonia,comorbidity
13668,10428194,111-13,17456-17465,pneumonia,comorbidity
41715,PMC3772525,78-60,12263-12272,pneumonia,_
42016,PMC3772525,89-12,13818-13827,pneumonia,_
42216,PMC3772525,97-22,14825-14834,pneumonia,_
68392,PMC4280857,133-22,20881-20890,pneumonia,_
79282,PMC4535917,89-13,14413-14422,pneumonia,_
79540,PMC4535917,100-9,15942-15951,pneumonia,_
98091,eichhorst2016,39-8,12436-12445,pneumonia,_
98511,eichhorst2016,52-19,14808-14817,pneumonia,_
106331,eichhorst2016,193-452,49999-50008,pneumonia,_
107101,eichhorst2016,193-1222,51881-51890,pneumonia,_
107966,eichhorst2016,196-492,54493-54502,pneumonia,_
108930,eichhorst2016,213-28,58739-58748,pneumonia,_
108970,eichhorst2016,213-68,58868-58877,pneumonia,_
126540,fischer2015,24-10,7231-7240,pneumonia,_
136146,hallek2010-3,34-3,10916-10925,pneumonia,_
141583,hallek2010-3,154-26,35003-35012,pneumonia,_
150596,1030698,113-28,19675-19684,pneumonia,_
152490,1030698,149-294,29437-29446,pneumonia,_
157285,nihms977597,51-126,7541-7550,pneumonia,_
163837,nihms977597,231-35,39476-39485,pneumonia,_
163864,nihms977597,232-18,39609-39618,pneumonia,_
180631,nejmoa1509388,227-182,40195-40204,pneumonia,_
180767,nejmoa1509388,227-318,40615-40624,pneumonia,_
188105,8589-Article,96-7,19094-19103,pneumonia,_
195665,s40880-018-0300-5,91-48,14169-14178,pneumonia,comorbidity
195764,s40880-018-0300-5,95-7,14566-14575,pneumonia,_
195793,s40880-018-0300-5,96-5,14714-14723,pneumonia,_
195952,s40880-018-0300-5,100-13,15291-15300,pneumonia,comorbidity
195981,s40880-018-0300-5,102-20,15451-15460,pneumonia,_
196348,s40880-018-0300-5,110-10,17142-17151,pneumonia,therapy\_group
211849,bcp,105-35,16569-16578,pneumonia,_
235104,jco,109-15,22016-22025,pneumonia,_
235320,jco,117-12,23296-23305,pneumonia,_
242400,JCO,31-5,8749-8758,pneumonia,_
244628,JCO,95-18,20617-20626,pneumonia,_
245289,JCO,102-23,23263-23272,pneumonia,_
246014,JCO,115-9,26969-26978,pneumonia,_
247834,JCO,148-257,36212-36221,pneumonia,_
297070,PMC2779118,103-10,16363-16372,pneumonia,_
297087,PMC2779118,104-16,16436-16445,pneumonia,_
297132,PMC2779118,105-7,16607-16616,pneumonia,_
300842,PMC2861142,86-9,14057-14066,pneumonia,_
314385,PMC3134602,78-7,12689-12698,pneumonia,_
314970,PMC3134602,99-25,15578-15587,pneumonia,_
322286,PMC4342187,12-3,2031-2040,pneumonia,_
325846,PMC4342187,129-10,21258-21267,pneumonia,_

In [69]:
nerdf['label'][nerdf['token']=='pneumonia'] = 'comorbidity'

In [70]:
nerdf[nerdf['token']=='neutropenia']

        article_id token_position char_position        token        label
5308      10428194          197-4   26048-26059  neutropenia  comorbidity
5327      10428194         198-11   26144-26155  neutropenia            _
5365      10428194          200-4   26395-26406  neutropenia  comorbidity
6019      10428194         225-26   29731-29742  neutropenia            _
6057      10428194         225-64   29882-29893  neutropenia            _
...            ...            ...           ...          ...          ...
300901  PMC2861142           88-6   14375-14386  neutropenia            _
301487  PMC2861142          110-1   17913-17924  neutropenia            _
322239  PMC4342187           11-9     1851-1862  neutropenia  comorbidity
323453  PMC4342187          49-10     9021-9032  neutropenia            _
325900  PMC4342187          133-9   21538-21549  neutropenia            _

[170 rows x 5 columns]

In [71]:
nerdf[nerdf['token']=='toxicity']

        article_id token_position char_position     token label
1154      10428194          49-21     4329-4337  toxicity     _
1435      10428194           59-7     5935-5943  toxicity     _
1587      10428194          62-23     6787-6795  toxicity     _
2192      10428194          85-22   10231-10239  toxicity     _
3582      10428194          135-7   17636-17644  toxicity     _
...            ...            ...           ...       ...   ...
311107  PMC2967470         183-27   29916-29924  toxicity     _
311682  PMC2967470         206-20   33541-33549  toxicity     _
316344  PMC3134602         142-24   23371-23379  toxicity     _
323426  PMC4342187          47-18     8880-8888  toxicity     _
323490  PMC4342187          50-25     9234-9242  toxicity     _

[190 rows x 5 columns]

In [72]:
nerdf[nerdf['token']=='lymphocyte']

        article_id token_position char_position       token label
1190      10428194           51-7     4527-4537  lymphocyte     _
1201      10428194          51-18     4597-4607  lymphocyte     _
3028      10428194         115-25   14782-14792  lymphocyte     _
3945      10428194         150-10   19621-19631  lymphocyte     _
3999      10428194         151-34   19909-19919  lymphocyte     _
...            ...            ...           ...         ...   ...
300452  PMC2861142           75-5   12055-12065  lymphocyte     _
313631  PMC3134602          50-12     8780-8790  lymphocyte     _
315714  PMC3134602         122-36   19791-19801  lymphocyte     _
315874  PMC3134602         127-16   20637-20647  lymphocyte     _
323282  PMC4342187          42-43     8032-8042  lymphocyte     _

[75 rows x 5 columns]

In [73]:
nerdf[(nerdf['token']=='toxicity') & (nerdf['label']!='_')]

        article_id token_position char_position     token           label
86324   PMC4643417           2-56       461-469  toxicity  therapy\_group
235135         jco          110-6   22202-22210  toxicity     comorbidity
236185         jco         139-65   27589-27597  toxicity     comorbidity

In [74]:
nerdf[(nerdf['token']=='neutropenia') & (nerdf['label']!='_')]

,article_id,token_position,char_position,token,label
5308,10428194,197-4,26048-26059,neutropenia,comorbidity
5365,10428194,200-4,26395-26406,neutropenia,comorbidity
13624,10428194,110-35,17258-17269,neutropenia,comorbidity
13662,10428194,111-7,17432-17443,neutropenia,comorbidity
14688,10428194,137-8,22178-22189,neutropenia,comorbidity
51384,PMC4114227,102-9,15273-15284,neutropenia,comorbidity
52896,PMC4114227,164-7,22906-22917,neutropenia,comorbidity
67601,PMC4280857,101-5,16923-16934,neutropenia,comorbidity
96774,eichhorst2016,14-2,4633-4644,neutropenia,comorbidity
116875,nihms-1536858,121-11,22201-22212,neutropenia,comorbidity
134859,hallek2010-3,9-11,3679-3690,neutropenia,comorbidity
150147,1030698,99-38,17884-17895,neutropenia,comorbidity
157088,nihms977597,48-18,6897-6908,neutropenia,comorbidity
173191,nejmoa1509388,16-45,2478-2489,neutropenia,comorbidity
195875,s40880-018-0300-5,98-31,15044-15055,neutropenia,comorbidity
198901,s40880-018-0300-5,143-8,27132-27143,neutropenia,therapy\_group
201737,s12185-019-02635-9,4-9,1457-1468,neutropenia,comorbidity
234992,jco,106-28,21547-21558,neutropenia,comorbidity
241341,JCO,13-22,2257-2268,neutropenia,comorbidity
244570,JCO,93-10,20294-20305,neutropenia,comorbidity
265788,1078-0432,89-5,14883-14894,neutropenia,comorbidity
265843,1078-0432,91-6,15137-15148,neutropenia,therapy\_group
265948,1078-0432,96-2,15893-15904,neutropenia,comorbidity
284278,1078-0432,73-19,5125-5136,neutropenia,comorbidity
284290,1078-0432,73-31,5174-5185,neutropenia,comorbidity
284324,1078-0432,75-5,5301-5312,neutropenia,comorbidity
286857,1078-0432,155-22,19738-19749,neutropenia,comorbidity
287158,1078-0432,166-44,21352-21363,neutropenia,comorbidity
287211,1078-0432,167-11,21539-21550,neutropenia,comorbidity
289428,1078-0432,239-37,34113-34124,neutropenia,comorbidity
322239,PMC4342187,11-9,1851-1862,neutropenia,comorbidity

In [75]:
nerdf[(nerdf['token']=='lymphocyte') & (nerdf['label']!='_')]

,article_id,token_position,char_position,token,label
34148,PMC3702397,1-23,145-155,lymphocyte,therapy\_group
204355,s12185-019-02635-9,79-28,15402-15412,lymphocyte,comorbidity

In [76]:
nerdf['label'][nerdf['token']=='toxicity'] = 'comorbidity'
nerdf['label'][nerdf['token']=='neutropenia'] = 'comorbidity'
nerdf['label'][nerdf['token']=='lymphocyte'] = 'comorbidity'

In [77]:
nerdf[nerdf['token']=='bcr-abl']

        article_id token_position char_position    token           label
24675   PMC3108904          28-28     3851-3858  bcr-abl               _
262257         bjh         293-84   52200-52207  bcr-abl               _
301865  PMC2876208            2-2       183-190  bcr-abl               _
302220  PMC2876208          18-17     1941-1948  bcr-abl               _
302279  PMC2876208          21-10     2263-2270  bcr-abl               _
302340  PMC2876208          23-10     2605-2612  bcr-abl               _
302395  PMC2876208          25-18     2882-2889  bcr-abl               _
302400  PMC2876208          25-23     2895-2902  bcr-abl        mutation
302493  PMC2876208          27-23     3426-3433  bcr-abl        mutation
302509  PMC2876208           28-7     3515-3522  bcr-abl        mutation
302539  PMC2876208          29-13     3671-3678  bcr-abl               _
302616  PMC2876208           33-2     4102-4109  bcr-abl               _
302662  PMC2876208          34-27     4372-4379  bcr-abl               _
302672  PMC2876208           35-4     4424-4431  bcr-abl               _
305202  PMC2876208         131-15   17692-17699  bcr-abl               _
305389  PMC2876208         138-13   18666-18673  bcr-abl  therapy\_group
305635  PMC2876208         147-29   20045-20052  bcr-abl  therapy\_group

In [78]:
nerdf[nerdf['token']=='fbta05']

       article_id token_position char_position   token           label
34225  PMC3702397           5-11       621-627  fbta05  therapy\_group
34253  PMC3702397            6-3       801-807  fbta05  therapy\_group
34312  PMC3702397           7-45     1186-1192  fbta05  therapy\_group
34763  PMC3702397          22-16     3925-3931  fbta05  therapy\_group
34789  PMC3702397           23-1     4092-4098  fbta05  therapy\_group
34830  PMC3702397           25-1     4321-4327  fbta05  therapy\_group
35060  PMC3702397          31-14     5676-5682  fbta05  therapy\_group
35106  PMC3702397           33-9     5977-5983  fbta05  therapy\_group
35128  PMC3702397          34-16     6074-6080  fbta05  therapy\_group
35197  PMC3702397          35-14     6438-6444  fbta05               _
35241  PMC3702397           37-7     6701-6707  fbta05               _
35268  PMC3702397          38-15     6846-6852  fbta05               _
35282  PMC3702397           40-2     6913-6919  fbta05  therapy\_group
35309  PMC3702397          41-21     7057-7063  fbta05               _
35359  PMC3702397           44-4     7309-7315  fbta05        mutation
35421  PMC3702397          47-13     7648-7654  fbta05               _
35443  PMC3702397          48-12     7763-7769  fbta05               _
35591  PMC3702397          52-58     8498-8504  fbta05               _
35623  PMC3702397           54-8     8658-8664  fbta05  therapy\_group
35813  PMC3702397           60-3     9727-9733  fbta05  therapy\_group
35832  PMC3702397           61-4     9844-9850  fbta05  therapy\_group
35863  PMC3702397           62-1   10011-10017  fbta05  therapy\_group
35971  PMC3702397          65-13   10615-10621  fbta05  therapy\_group
36010  PMC3702397          66-23   10853-10859  fbta05  therapy\_group
36044  PMC3702397          67-14   11043-11049  fbta05  therapy\_group
36058  PMC3702397           68-5   11126-11132  fbta05  therapy\_group
36079  PMC3702397           69-3   11269-11275  fbta05  therapy\_group
36096  PMC3702397          69-20   11374-11380  fbta05               _
36151  PMC3702397          71-23   11704-11710  fbta05               _
36165  PMC3702397           72-6   11791-11797  fbta05  therapy\_group
36180  PMC3702397          72-21   11882-11888  fbta05               _
36202  PMC3702397          73-13   12032-12038  fbta05               _
36239  PMC3702397          74-33   12270-12276  fbta05               _
36275  PMC3702397          75-11   12495-12501  fbta05  therapy\_group
36304  PMC3702397          76-21   12640-12646  fbta05  therapy\_group
36334  PMC3702397          77-12   12825-12831  fbta05  therapy\_group
36416  PMC3702397           80-8   13263-13269  fbta05               _
36445  PMC3702397          81-17   13423-13429  fbta05               _
36452  PMC3702397          81-24   13467-13473  fbta05               _
36591  PMC3702397          84-23   14254-14260  fbta05               _
37173  PMC3702397          106-4   17228-17234  fbta05  therapy\_group
37228  PMC3702397          108-7   17510-17516  fbta05  therapy\_group
37242  PMC3702397          109-1   17588-17594  fbta05  therapy\_group
37306  PMC3702397          113-7   17905-17911  fbta05               _
37355  PMC3702397         116-24   18145-18151  fbta05  therapy\_group
37383  PMC3702397          117-6   18235-18241  fbta05  therapy\_group
37465  PMC3702397          118-5   18462-18468  fbta05  therapy\_group
37628  PMC3702397         124-16   19289-19295  fbta05               _
38364  PMC3702397         145-15   23190-23196  fbta05               _
38544  PMC3702397         152-22   24203-24209  fbta05  therapy\_group
38594  PMC3702397          155-2   24488-24494  fbta05  therapy\_group
38681  PMC3702397          158-4   24967-24973  fbta05  therapy\_group
38929  PMC3702397         170-15   26403-26409  fbta05  therapy\_group
38961  PMC3702397          171-7   26578-26584  fbta05               _
39089  PMC3702397          174-3   27378-27384  fbta05  therapy\_group
39384  PMC3702397         184-16   29091-29097  fbta05               _
39456  PMC3702397         188-12   29496-29502  fbta05               _

In [79]:
nerdf['label'][nerdf['token']=='fbta05'] = 'therapy\_group'

In [80]:
nerdf[nerdf['token']=='meg']

        article_id token_position char_position token           label
316942  PMC2892453           8-27     1362-1365   meg        mutation
318948  PMC2892453          75-16   12572-12575   meg               _
318957  PMC2892453           76-4   12607-12610   meg  therapy\_group
319058  PMC2892453           80-5   13125-13128   meg  therapy\_group
319079  PMC2892453          80-26   13199-13202   meg               _
320168  PMC2892453         109-17   19237-19240   meg               _

In [82]:
nerdf[nerdf['token']=='vincristine']

,article_id,token_position,char_position,token,label
14667,10428194,136-40,22043-22054,vincristine,therapy\_group
22555,PMC2827854,82-17,10249-10260,vincristine,_
46918,PMC4102435,113-23,17300-17311,vincristine,_
46964,PMC4102435,114-15,17567-17578,vincristine,_
47109,PMC4102435,119-13,18436-18447,vincristine,_
120962,nihms-1536858,283-20,43350-43361,vincristine,_
234185,jco,88-58,17701-17712,vincristine,nam
244259,JCO,80-249,18684-18695,vincristine,_
244270,JCO,80-260,18753-18764,vincristine,_
248638,JCO,184-26,40898-40909,vincristine,_
248692,JCO,186-22,41259-41270,vincristine,_
248858,JCO,192-25,42240-42251,vincristine,_
284789,1078-0432,92-9,8024-8035,vincristine,_
289248,1078-0432,237-7,33183-33194,vincristine,_
289251,1078-0432,237-10,33209-33220,vincristine,_
290363,1078-0432,276-9,39394-39405,vincristine,_
290988,1078-0432,311-1,42177-42188,vincristine,_

In [84]:
nerdf[nerdf['token']=='doxorubicin']

,article_id,token_position,char_position,token,label
46923,PMC4102435,113-28,17323-17334,doxorubicin,_
120960,nihms-1536858,283-18,43337-43348,doxorubicin,_
234183,jco,88-56,17688-17699,doxorubicin,nam
241640,JCO,18-16,4121-4132,doxorubicin,therapy\_group
244257,JCO,80-247,18671-18682,doxorubicin,_
248636,JCO,184-24,40885-40896,doxorubicin,_
248856,JCO,192-23,42227-42238,doxorubicin,_
290361,1078-0432,276-7,39381-39392,doxorubicin,_
291584,1078-0432,342-9,44948-44959,doxorubicin,_

In [85]:
nerdf[nerdf['token']=='prednisone']

           article_id token_position char_position       token           label
14669        10428194         136-42   22060-22070  prednisone  therapy\_group
120965  nihms-1536858         283-23   43367-43377  prednisone               _
234188            jco          88-61   17718-17728  prednisone             nam
243322            JCO          61-30   14024-14034  prednisone             nam
244262            JCO         80-252   18701-18711  prednisone               _
244273            JCO         80-263   18770-18780  prednisone               _
248641            JCO         184-29   40915-40925  prednisone               _
248695            JCO         186-25   41276-41286  prednisone               _
248861            JCO         192-28   42257-42267  prednisone               _
271425              j           89-9   14677-14687  prednisone               _
290366      1078-0432         276-12   39411-39421  prednisone               _
291586      1078-0432         342-11   44964-44974  prednisone               _
323185     PMC4342187         38-106     7468-7478  prednisone               _

In [87]:
nerdf[(nerdf['token']=='progression') & (nerdf['label']!='_')]

        article_id token_position char_position        token           label
86321   PMC4643417           2-53       433-444  progression  therapy\_group
318357  PMC2892453          55-13     9317-9328  progression             nam

In [88]:
nerdf[(nerdf['token']=='treatment') & (nerdf['label']!='_')]

        article_id token_position char_position      token           label
37694   PMC3702397         126-25   19603-19612  treatment        followup
51280   PMC4114227           96-7   14727-14736  treatment  therapy\_group
319310  PMC2892453          86-11   14450-14459  treatment  therapy\_group
320755  PMC2892453         129-40   22554-22563  treatment             nam
321078  PMC2892453         144-19   24367-24376  treatment             nam

In [89]:
nerdf[(nerdf['token']=='disease') & (nerdf['label']!='_')]

        article_id token_position char_position    token           label
31373   PMC3579463          62-15   10930-10937  disease             nam
49590   PMC4114227          36-19     6266-6273  disease             nam
86320   PMC4643417           2-52       425-432  disease  therapy\_group
301020  PMC2861142          93-14   15095-15102  disease             nam
301829  PMC2861142         121-25   20038-20045  disease             nam
318356  PMC2892453          55-12     9309-9316  disease             nam
324305  PMC4342187          88-38   13832-13839  disease             nam

In [90]:
nerdf['label'][nerdf['token']=='disease'] = 'nam'

In [94]:
nerdf.to_csv('/content/drive/MyDrive/GitHub/exBERT/data/preprocessed_data/ner_data_step2.csv', index=True)

In [92]:
ent_list = nerdf[['token',	'label']]
ent_list

                  token label
0       next-generation     _
1            sequencing     _
2                     (     _
3                   ngs     _
4                     )     _
...                 ...   ...
327216         patients     _
327217               is     _
327218            being     _
327219      re-assessed     _
327220                .     _

[327221 rows x 2 columns]

In [93]:
ent_list.to_csv('/content/drive/MyDrive/GitHub/exBERT/data/preprocessed_data/ner_data_step2narrow.csv', index=True)